github: improve testing matrix
* Combine multiple OS runs into a single matrix strategy
* Ensure crate is tested with all feature combinations
* Split library and binary tests

diff --git a/.github/workflows/rust_test.yml b/.github/workflows/rust_test.yml
--- a/.github/workflows/rust_test.yml
+++ b/.github/workflows/rust_test.yml
@@ -8,35 +8,24 @@ on:
 
 env:
   CARGO_TERM_COLOR: always
+  RUST_BACKTRACE: 1
 
 jobs:
-  test_linux:
-    runs-on: ubuntu-latest
+  test_sameold:
+    strategy:
+      matrix:
+        os: [ubuntu-latest, windows-latest, macos-latest]
+        features: ['', 'chrono']
+
+    runs-on: ${{ matrix.os }}
+
     steps:
     - uses: actions/checkout@v3
-    - name: Record environment
-      run: cat /etc/os-release && cargo version
-    - uses: actions/cache@v3
-      name: Restore Rust cache
-      with:
-        path: |
-          ~/.cargo/bin/
-          ~/.cargo/registry/index/
-          ~/.cargo/registry/cache/
-          ~/.cargo/git/db/
-          target/
-        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
-    - name: Build
-      run: cargo build --verbose
-    - name: Run tests
-      run: cargo test --verbose
-  test_windows:
-    runs-on: windows-latest
-    steps:
-    - uses: actions/checkout@v3
+
     - name: Record environment
       shell: bash
       run: cargo version
+
     - uses: actions/cache@v3
       name: Restore Rust cache
       with:
@@ -47,29 +36,51 @@ jobs:
           ~/.cargo/git/db/
           target/
         key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
-    - name: Build
+
+    - name: Build and test sameold
       shell: bash
-      run: cargo build --verbose
-    - name: Run tests
-      shell: bash
-      run: cargo test --verbose
-  test_macos:
-    runs-on: macos-latest
+      run: |
+        cargo test -p sameold --verbose --no-default-features --features "${{ matrix.features }}"
+
+  test_samedec:
+    strategy:
+      matrix:
+        os: [ubuntu-latest, windows-latest, macos-latest]
+
+    runs-on: ${{ matrix.os }}
+
     steps:
-      - uses: actions/checkout@v3
-      - name: Record environment
-        run: cargo version
-      - uses: actions/cache@v3
-        name: Restore Rust cache
-        with:
-          path: |
-            ~/.cargo/bin/
-            ~/.cargo/registry/index/
-            ~/.cargo/registry/cache/
-            ~/.cargo/git/db/
-            target/
-          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
-      - name: Build
-        run: cargo build --verbose
-      - name: Run tests
-        run: cargo test --verbose
+    - uses: actions/checkout@v3
+
+    - name: Record environment
+      shell: bash
+      run: cargo version
+
+    - uses: actions/cache@v3
+      name: Restore Rust cache
+      with:
+        path: |
+          ~/.cargo/bin/
+          ~/.cargo/registry/index/
+          ~/.cargo/registry/cache/
+          ~/.cargo/git/db/
+          target/
+        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
+
+    - name: Build and test samedec
+      shell: bash
+      run: |
+        cargo test -p samedec --verbose
+
+    - name: Run integration tests
+      shell: bash
+      run: |
+        EXPECT="$(cat <sample/long_message.22050.s16le.txt)" &&
+        OUT="$(cargo run -p samedec -- -r 22050 <sample/long_message.22050.s16le.bin)" &&
+        echo "$OUT" &&
+        if [ "$OUT" = "$EXPECT" ]; then
+          echo "PASS";
+        else
+          echo "FAIL!";
+          exit 1;
+        fi
